# Generated by Django 3.0.3 on 2022-04-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='function',
            field=models.CharField(blank=True, max_length=40000),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget',
            field=models.CharField(blank=True, max_length=40000),
        ),
    ]
