# Generated by Django 3.0.3 on 2022-06-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220415_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
