# Generated by Django 3.0.3 on 2022-06-16 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220614_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='inmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bet', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='widget',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inmodel'),
        ),
    ]
