# Generated by Django 3.0.3 on 2022-06-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220616_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmodel',
            name='bet',
            field=models.IntegerField(blank=True, max_length=10000),
        ),
    ]
