# Generated by Django 3.0.3 on 2022-06-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220616_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
