# Generated by Django 3.0.3 on 2022-06-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220616_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='game',
        ),
        migrations.DeleteModel(
            name='inmodel',
        ),
    ]
